### ISSUE TITLE
metadata is indented too much

### ISSUE THREAD

**Issue by mattmoor** [csantanapr/knative-tekton#2]
```
apiVersion: tekton.dev/v1beta1
kind: Task
  metadata:
    name: deploy
spec:
```

in the main README.md

**Comment by csantanapr** [comment]
let me double check something mess up all the tekton yamls in the readme they are correct in the files

**Comment by csantanapr** [comment]
Fixed a bunch of indentation problems in the Readme here https://github.com/csantanapr/knative-tekton/commit/b19b8c70bac9d0da4fc5bba5953086c50d05ba79
